### ISSUE TITLE
Why not libModSec with the ModSecurity-nginx connector.

### ISSUE THREAD

**Issue by zimmerle** [theonemule/docker-waf#1]
I notice that it is not using the ModSecurity-nginx connector yet. Is that any specific reason for that?

ModSecurity-nginx: 
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by theonemule** [comment]
No reason really. Mostly because I was porting my old Ubuntu knowledge to containers. I really haven't used the connector. I'll see if I can make it work with that l.

**Comment by zimmerle** [comment]
It will be great to have a container with v3.

**Comment by theonemule** [comment]
Cool.

**Comment by oxr463** [comment]
This was closed, but was it ever implemented?
