### ISSUE TITLE
WAF exited with code 127 - nginx not found

### ISSUE THREAD

**Issue by I3artko** [theonemule/docker-waf#5]
Hi, I'm trying to run demo environment with Your solution, but I got stuck because of the error: 

```
waf_1  | /bin/sh: 1: nginx: not found
docker-waf_waf_1 exited with code 127
```
All I did to run was to rename WAF Dokerfile.single to Dockerfile and next to simply to up docker-compose.yml file. 
It seems like nginx inside of WAF docker doesn't work properly.

**Comment by theonemule** [comment]
Sounds to me like nginx didn't compile. Rerun the build and see of there is an error in the build process.

**Comment by I3artko** [comment]
Yep, I don't know how it is possible that didn't notice it before. 

Indeed, while building few errors occurred:

 `src/core/ngx_murmurhash.c: In function 'ngx_murmur_hash2':
src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[2] << 16;
         ~~^~~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:38:5: note: here
     case 2:
     ^~~~
src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[1] << 8;
         ~~^~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:40:5: note: here
     case 1:
     ^~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/src/core/ngx_murmurhash.o] Error 1
`
and `src/core/ngx_murmurhash.c: In function 'ngx_murmur_hash2':
src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[2] << 16;
         ~~^~~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:38:5: note: here
     case 2:
     ^~~~
src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[1] << 8;
         ~~^~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:40:5: note: here
     case 1:
     ^~~~
`

**Comment by theonemule** [comment]
Can you change the image in FROM to ubuntu:16.04

**Comment by I3artko** [comment]
It almost succeed. Now it returns: 

```
Attaching to docker-waf_app_1-old, docker-waf_waf_1
waf_1  | nginx: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
docker-waf_waf_1 exited with code 127

app_1  | 
app_1  | > demo-app@1.0.0 start /usr/src/app
app_1  | > node index.js
app_1  | 
app_1  | Listening on port 80
```

**Comment by I3artko** [comment]
Well, the sample app seems to work properly. After change, it doesn't start anymore. And the problem with library shortage persists.

**Comment by theonemule** [comment]
You don't need the sample app for the WAF. Use any http app.

**Comment by theonemule** [comment]
Get the docker logs for the WAF and post them here.

**Comment by I3artko** [comment]
Well, I know I don't need this exact app, but the case is that app works properly. 

I can not obtain any logs because of the fact that it did not start. As I posted before: 

`waf_1  | nginx: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
docker-waf_waf_1 exited with code 127`

**Comment by theonemule** [comment]
You can run the WAF in interactive mode to get the output.

**Comment by theonemule** [comment]
Not sure if you're still having problems, but I've updated the build scripts with a newer version of NGINX and Ubuntu and it appears to be in good order.
