### ISSUE TITLE
Error build waf

### ISSUE THREAD

**Issue by artsur** [theonemule/docker-waf#6]
When i try to build waf: `docker-compose build waf`  the proccess ending:
`configuring additional modules`
`adding module in /usr/src/modsecurity/nginx/modsecurity`
`./configure: error: no /usr/src/modsecurity/nginx/modsecurity/config was found`
`make: *** No rule to make target 'build', needed by 'default'.  Stop.`
`make: *** No rule to make target 'install'.  Stop.`
`ERROR: Service 'waf' failed to build: The command '/bin/sh -c chmod +x /build.multi.sh && /bin/bash -c "source /build.multi.sh"' returned a non-zero code: 2`

**Comment by theonemule** [comment]
Looks like the bash interpreter is having problems finding git. Strange.

I moved the build back into the Dockerfile and ran it and everything appears to be working now.
