### ISSUE TITLE
how to use env in nginx.conf

### ISSUE THREAD

**Issue by lixiaoabc** [theonemule/docker-waf#7]
[root@94 waf]# docker exec -it dockerwaf_waf_1 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=36e4fa0ae9b9
TERM=xterm
MY_PROXY_SITE=94.191.72.242:9000
HOME=/root

this is my nginx.conf 
proxy_pass http://${MY_PROXY_SITE}/;

root@36e4fa0ae9b9:/usr/local/nginx/conf# nginx -t 
nginx: [emerg] unknown "my_proxy_site" variable
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

**Comment by theonemule** [comment]
Directly accessing environmental variables in an NGINX config file isn't natively supported. Using sed to replace a token in the config file or using LUA or PERL to get variables into an NGINX configuration file.

https://web.archive.org/web/20170712003702/https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html

**Comment by lixiaoabc** [comment]
> Directly accessing environmental variables in an NGINX config file isn't natively supported. Using sed to replace a token in the config file or using LUA or PERL to get variables into an NGINX configuration file.
> 
> https://web.archive.org/web/20170712003702/https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html

I Can't open this link
how to Using sed to replace a token in the config file

This is my Docker file，dockerwaf_waf is your  image
FROM dockerwaf_waf
COPY nginx.conf /usr/local/nginx/conf/nginx.conf
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 777 /usr/local/nginx/conf/nginx.conf
RUN chmod +x /usr/local/bin/entrypoint.sh
#入口
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
#命令
CMD /usr/local/bin/entrypoint.sh

entrypoint.sh
sed -i 's/MY_PROXY_SITE/'$MY_PROXY_SITE'/g' /usr/local/nginx/conf/nginx.conf
    /usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf

but I Can't start the container
