### ISSUE TITLE
Use official NGINX container image as base

### ISSUE THREAD

**Issue by oxr463** [theonemule/docker-waf#8]
See: https://hub.docker.com/_/nginx

**Comment by oxr463** [comment]
Let me know if you have the bandwidth or even the desire to do this, and I can submit a PR.

**Comment by theonemule** [comment]
I compile it from the source because the base image isn't compiled with support for OWASP. It was really the only reason I even made this project...

**Comment by oxr463** [comment]
Not sure if you saw this, https://hub.docker.com/r/owasp/modsecurity-crs

**Comment by theonemule** [comment]
Cool. If that works better, then use it. This project has been waning for some time, which I'm perfectly fine with. I wrote it to serve a need. If it's been met in other ways, then cool.
