### ISSUE TITLE
ModSecurityEnabled on Left An Error

### ISSUE THREAD

**Issue by msq6323013** [theonemule/docker-waf#9]
nginx: [emerg] unknown directive "ModSecurityEnabled" in /etc/nginx/nginx.conf:44

**Comment by msq6323013** [comment]
load_module /etc/nginx/modules/ngx_http_modsecurity_module.so; ?

**Comment by msq6323013** [comment]
cp ./objs/ngx_http_modsecurity_module.so /etc/nginx/modules**/**

**Comment by msq6323013** [comment]
ngx_http_modsecurity_module.so" is not binary compatible

**Comment by theonemule** [comment]
You caught me in mid flight with changes. :) I pushed some update to v3 today.

Thanks
